### ISSUE TITLE
Illustration for my book

### ISSUE THREAD

**Issue by aburkov** [snakers4/playing_with_vae#1]
Hi,

I'm writing a book on machine learning http://themlbook.com/wiki/doku.php and I would like to use your illustration of PCA vs UMAP vs VAE. Would it be possible?

If yes, could you send me this illustration https://github.com/snakers4/playing_with_vae/blob/master/compare.png in eps or pdf format? Of course, I will properly indicate your authorship in the book.

Andriy

**Comment by snakers4** [comment]
Hi,

Yes, why not, use it.
This is the purpose of this repo after all.

But the thing is - to change the format of the image I believe I would have to redo all the steps in my notebook.

I believe this PNG is in high quality, or do you specifically need it in vector format?

**Comment by aburkov** [comment]
I have implemented that myself after all, but thank you very much anyway!

**Comment by snakers4** [comment]
![default](https://user-images.githubusercontent.com/12515440/48687787-f40e3a00-ebd3-11e8-9875-850eeb526262.png)
